run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  govet:
    enable-all: false
    enable:
      - atomic
      - bools
      - buildtag
      - errorsas
      - nilfunc
      - printf
      - unreachable

issues:
  exclude-dirs:
    - testdata
    - pb_data
  max-issues-per-linter: 50
  max-same-issues: 5
